# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
combobox='''
QComboBox{
	background-color:None;
	border-radius:10px;
}
QComboBox::drop-down{
	width:30px;
	border-top-right-radius:10px;
	border-bottom-right-radius:10px;
	background-color:None;
}
QComboBox::down-arrow{
	border-image:url(:/icon/down.png)
}
QComboBox QAbstractItemView{
	outline:0px;
	background:None;
	border-radius:8px;
	selection-background-color:grey;
}
QComboBox QAbstractItemView::item{
	background-color:None;
	min-height:30px;
}
QComboBox QScrollBar::vertical{
	width:3px;
	background-color:white;
	border:None;
}
QComboBox QScrollBar::handle::vertical{
	/*border-radius:3px;*/
	background-color:grey;
}
QComboBox QScrollBar::handle::vertical::hover{
	background-color:grey;
}
QComboBox QScrollBar::add-line::vertical{
        background-color:white;
	border:None;
}
QComboBox QScrollBar::sub-line::vertical{
        background-color:white;
	
}
'''

#from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import (
    Qt,
    QRect,
    QCoreApplication,
    QMetaObject
)

from PyQt5.QtWidgets import (
    QWidget,
    QMainWindow,
    QPushButton,
    QLabel,
    QComboBox,
    QLineEdit,
    QRadioButton,
    QToolButton,
    QApplication,
)

from PyQt5.QtGui import (
    QFont,
    QCursor,
)

class MyWindow(QWidget):
    def __init__(self, parent=None) -> None:
        super(MyWindow,self).__init__(parent)
        
    #---gtj 实现鼠标拖拽功能
    def mousePressEvent(self, event):
        self.pressX = event.x()    #记录鼠标按下的时候的坐标
        self.pressY = event.y()

    def mouseMoveEvent(self, event):
        x = event.x()
        y = event.y()   #获取移动后的坐标
        moveX = x-self.pressX
        moveY = y-self.pressY  #计算移动了多少
 
        positionX = self.frameGeometry().x() + moveX
        positionY = self.frameGeometry().y() + moveY    #计算移动后主窗口在桌面的位置
        self.move(positionX, positionY)
class Ui_login(object):
    def setupUi(self, win:QWidget):
        login=QWidget(win)
        login.setObjectName("login")
        login.resize(483, 465)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setBold(False)
        font.setWeight(50)
        login.setFont(font)
        login.setStyleSheet("QWidget{\n"
"    /*background-color: rgb(0, 170, 255);*/\n"
"    border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(93, 0, 255, 255), stop:1 rgba(242, 0, 255, 255));\n"
"}")
        self.into = QPushButton(login)
        self.into.setGeometry(QRect(119, 360, 283, 41))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.into.setFont(font)
        self.into.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 85, 255);\n"
"    border-radius:20px;\n"
"    border-width:4px;\n"
"    color:white;\n"
"    border-color:rgba(255,255,255,30);\n"
"}\n"
"")
        self.into.setObjectName("into")
        self.maintitle = QLabel(login)
        self.maintitle.setGeometry(QRect(170, 40, 161, 61))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.maintitle.setFont(font)
        self.maintitle.setStyleSheet("color:white;\n"
"background-color:None;")
        self.maintitle.setAlignment(Qt.AlignCenter)
        self.maintitle.setObjectName("maintitle")
        self.user = QLabel(login)
        self.user.setGeometry(QRect(155, 150, 81, 31))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.user.setFont(font)
        self.user.setStyleSheet("color:white;\n"
"background-color:None;")
        self.user.setObjectName("user")
        self.userch = QComboBox(login)
        self.userch.view().setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.userch.view().setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.userch.setGeometry(QRect(250, 156, 111, 25))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.userch.setFont(font)
        self.userch.setStyleSheet(combobox)
        self.userch.setMaxVisibleItems(5)
        self.userch.setDuplicatesEnabled(False)
        self.userch.setObjectName("userch")
        self.userch.addItem("")
        self.userch.addItem("")
        self.userch.addItem("")
        self.userch.addItem("")
        self.userch.addItem("")
        self.userch.addItem("")
        self.userch.addItem("")
        self.userch.addItem("")
        self.userch.addItem("")
        self.userch.addItem("")
        self.userch.addItem("")
        self.password = QLabel(login)
        self.password.setGeometry(QRect(155, 230, 81, 31))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:None;\n"
"color:white;")
        self.password.setObjectName("pass")
        self.passenter = QLineEdit(login)
        self.passenter.setGeometry(QRect(249, 237, 112, 23))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.passenter.setFont(font)
        self.passenter.setCursor(QCursor(Qt.IBeamCursor))
        self.passenter.setStyleSheet("background-color:None;\n"
"border-radius:10px;")
        self.passenter.setMaxLength(10)
        self.passenter.setEchoMode(QLineEdit.Password)
        self.passenter.setAlignment(Qt.AlignCenter)
        self.passenter.setObjectName("passenter")
        self.mindpass = QRadioButton(login)
        self.mindpass.setGeometry(QRect(310, 310, 101, 16))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.mindpass.setFont(font)
        self.mindpass.setStyleSheet("background-color:None;\n"
"color:white;")
        self.mindpass.setObjectName("mindpass")
        self.usertool = QToolButton(login)
        self.usertool.setGeometry(QRect(135, 310, 61, 16))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.usertool.setFont(font)
        self.usertool.setStyleSheet("background-color:None;\n"
"color:white;")
        self.usertool.setObjectName("usertool")
        self.close = QPushButton(login)
        self.close.setGeometry(QRect(434, 10, 41, 31))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(17)
        self.close.setFont(font)
        self.close.setStyleSheet("background-color:None;\n"
"color:white;")
        self.close.setObjectName("close")

        self.retranslateUi(login)
        self.close.clicked.connect(win.close) # type: ignore
        QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Erichat"))
        self.into.setText(_translate("login", "进入Erichat"))
        self.maintitle.setText(_translate("login", "Sign in"))
        self.user.setText(_translate("login", "账号："))
        self.userch.setItemText(0, _translate("login", "mc"))
        self.userch.setItemText(1, _translate("login", "users"))
        self.userch.setItemText(2, _translate("login", "jvav"))
        self.userch.setItemText(3, _translate("login", "pygame"))
        self.userch.setItemText(4, _translate("login", "a1"))
        self.userch.setItemText(5, _translate("login", "a2"))
        self.userch.setItemText(6, _translate("login", "linux"))
        self.userch.setItemText(7, _translate("login", "114"))
        self.userch.setItemText(8, _translate("login", "because520"))
        self.userch.setItemText(9, _translate("login", "a3"))
        self.userch.setItemText(10, _translate("login", "admin"))
        self.password.setText(_translate("login", "密码："))
        self.mindpass.setText(_translate("login", "记住密码"))
        self.usertool.setText(_translate("login", "管理账号"))
        self.close.setText(_translate("login", "×"))
from img import *


if __name__ == "__main__":
    from sys import argv,exit
    app = QApplication(argv)
    app.setStyle('windows')
    login = MyWindow()
    login.setGeometry(200,200,483,465)
    login.setWindowFlags(Qt.WindowType.FramelessWindowHint)
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    exit(app.exec_())
