# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import (
    Qt,
    QRect,
    QCoreApplication,
    QMetaObject
)

from PyQt5.QtWidgets import (
    QWidget,
    QMainWindow,
    QPushButton,
    QLabel,
    QLineEdit,
    QToolButton,
    QApplication,
)

from PyQt5.QtGui import (
    QFont,
)

from mywidgets import MyWindow,lesshint


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(483, 465)
        font = QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    /*background-color: rgb(0, 170, 255);*/\n"
"    border-top-left-radius:15px;\n"
"    border-top-right-radius:15px;\n"
"    border-bottom-left-radius:15px;\n"
"    border-bottom-right-radius:15px;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(93, 0, 255, 255), stop:1 rgba(242, 0, 255, 255));;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QRect(170, 40, 166, 61))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;\n"
"background-color:None;")
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setGeometry(QRect(155, 150, 81, 31))
        font = QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;\n"
"background-color:None;")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QRect(249, 157, 112, 23))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:None;\n"
"border-radius:10px;")
        self.lineEdit.setMaxLength(10)
        self.lineEdit.setAlignment(Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setGeometry(QRect(155, 230, 81, 31))
        font = QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;\n"
"background-color:None;")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QRect(249, 237, 112, 23))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:None;\n"
"border-radius:10px;")
        self.lineEdit_2.setMaxLength(10)
        self.lineEdit_2.setEchoMode(QLineEdit.Password)
        self.lineEdit_2.setAlignment(Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QRect(119, 340, 283, 41))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 85, 255);\n"
"    border-radius:20px;\n"
"    border-width:4px;\n"
"    color:white;\n"
"    border-color:rgba(255,255,255,30);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.toolButton = QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QRect(135, 305, 61, 16))
        self.toolButton.setStyleSheet("background-color:None;\n"
"color:white;")
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QRect(347, 305, 37, 18))
        self.toolButton_2.setStyleSheet("background-color:None;\n"
"color:white;")
        self.toolButton_2.setObjectName("toolButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "新建账号"))
        self.label.setText(_translate("MainWindow", "新建账号"))
        self.label_2.setText(_translate("MainWindow", "昵称："))
        self.label_3.setText(_translate("MainWindow", "密码："))
        self.pushButton.setText(_translate("MainWindow", "重启Erichat"))
        self.toolButton.setText(_translate("MainWindow", "名称规则"))
        self.toolButton_2.setText(_translate("MainWindow", "返回"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = MyWindow()
    lesshint(MainWindow)
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
