# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import (
    Qt,
    QRect,
    QCoreApplication,
    QMetaObject
)

from PyQt5.QtWidgets import (
    QPushButton,
    QLabel,
    QLineEdit,
    QRadioButton,
    QToolButton,
    QApplication,
    QWidget,
)

from PyQt5.QtGui import (
    QFont,
    QCursor,
)

from mywidgets import MyWindow,lesshint

class Ui_login(object):
    def setupUi(self, MainWindow):
        login = QWidget(MainWindow)
        MainWindow.setObjectName("login")
        MainWindow.resize(483, 465)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setBold(False)
        font.setWeight(50)
        login.setFont(font)
        login.setStyleSheet("QWidget{\n"
"    /*background-color: rgb(0, 170, 255);*/\n"
"    border-top-left-radius:15px;\n"
"    border-top-right-radius:15px;\n"
"    border-bottom-left-radius:15px;\n"
"    border-bottom-right-radius:15px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(93, 0, 255, 255), stop:1 rgba(242, 0, 255, 255));\n"
"}")
        self.into = QPushButton(login)
        self.into.setGeometry(QRect(119, 360, 283, 41))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.into.setFont(font)
        self.into.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 85, 255);\n"
"    border-radius:20px;\n"
"    border-width:4px;\n"
"    color:white;\n"
"    border-color:rgba(255,255,255,30);\n"
"}\n"
"")
        self.into.setObjectName("into")
        self.maintitle = QLabel(login)
        self.maintitle.setGeometry(QRect(170, 40, 161, 61))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.maintitle.setFont(font)
        self.maintitle.setStyleSheet("color:white;\n"
"background-color:None;")
        self.maintitle.setAlignment(Qt.AlignCenter)
        self.maintitle.setObjectName("maintitle")
        self.user = QLabel(login)
        self.user.setGeometry(QRect(155, 150, 81, 31))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.user.setFont(font)
        self.user.setStyleSheet("color:white;\n"
"background-color:None;")
        self.user.setObjectName("user")
        self.pass_ = QLabel(login)
        self.pass_.setGeometry(QRect(155, 230, 81, 31))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pass_.setFont(font)
        self.pass_.setStyleSheet("background-color:None;\n"
"color:white;")
        self.pass_.setObjectName("pass")
        self.passenter = QLineEdit(login)
        self.passenter.setGeometry(QRect(249, 237, 112, 23))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.passenter.setFont(font)
        self.passenter.setCursor(QCursor(Qt.IBeamCursor))
        self.passenter.setStyleSheet("background-color:None;\n"
"border-radius:10px;")
        self.passenter.setMaxLength(10)
        self.passenter.setEchoMode(QLineEdit.Password)
        self.passenter.setAlignment(Qt.AlignCenter)
        self.passenter.setObjectName("passenter")
        self.mindpass = QRadioButton(login)
        self.mindpass.setGeometry(QRect(310, 310, 101, 16))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.mindpass.setFont(font)
        self.mindpass.setStyleSheet("background-color:None;\n"
"color:white;")
        self.mindpass.setObjectName("mindpass")
        self.usertool = QToolButton(login)
        self.usertool.setGeometry(QRect(135, 310, 61, 16))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.usertool.setFont(font)
        self.usertool.setStyleSheet("background-color:None;\n"
"color:white;")
        self.usertool.setObjectName("usertool")
        self.close = QPushButton(login)
        self.close.setGeometry(QRect(434, 10, 41, 31))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.close.setFont(font)
        self.close.setStyleSheet("background-color:None;\n"
"color:white;")
        self.close.setObjectName("close")
        self.lineEdit = QLineEdit(login)
        self.lineEdit.setGeometry(QRect(249, 157, 112, 23))
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:None;\n"
"border-radius:10px;")
        self.lineEdit.setMaxLength(10)
        self.lineEdit.setAlignment(Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")

        MainWindow.setCentralWidget(login)

        self.retranslateUi(MainWindow)
        self.close.clicked.connect(MainWindow.close) # type: ignore
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, login):
        _translate = QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Erichat"))
        self.into.setText(_translate("login", "进入Erichat"))
        self.maintitle.setText(_translate("login", "Sign in"))
        self.user.setText(_translate("login", "账号："))
        self.pass_.setText(_translate("login", "密码："))
        self.mindpass.setText(_translate("login", "记住密码"))
        self.usertool.setText(_translate("login", "管理账号"))
        self.close.setText(_translate("login", "×"))
#from img import *


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    login = MyWindow()
    lesshint(login)
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec_())
